### ISSUE TITLE
[feature request] IP restrictions

### ISSUE THREAD

**Issue by lakano** [mafzst/tunack#5]
Hi !
Thanks a lot for your project :+1: 
With this annotations method, do you known if it's possible to restrict the access to this port to a list of specific IP addresses please?

**Comment by tuarrep** [comment]
This is just a wrapper around Nginx config map https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/exposing-tcp-udp-services.md

It seems to not be possible in the main project. So for now here it's not possible too.

**Comment by lakano** [comment]
Ok thanks
